# Allows compiling to work from the project-level.
contracts_folder: tests/contracts/passing_contracts

# Specify a dependency to use in Vyper imports.
dependencies:
  - name: exampledependency
    local: ./tests/ExampleDependency

  # NOTE: Snekmate does not need to be listed here since
  # it is installed in site-packages. However, we include it
  # to show it doesn't cause problems when included.
  - python: snekmate
    config_override:
      contracts_folder: .

vyper:
  enable_decimals: true
