import ape

from ape_vyper.exceptions import FallbackNotDefinedError, NonPayableError


def test_happy_path(contract, account):
    """
    Covers some implicit statements as well two source statements.
    """
    receipt = contract.foo_method(5, 6, sender=account)
    assert receipt.return_value is True


def test_sad_path(contract, account):
    """
    Covers some implicit statements as well as one source statement.
    """
    with ape.reverts(dev_message="dev: sub-zero"):
        contract.foo_method(0, 1, sender=account)


def test_non_payable(contract, account):
    """
    Coverage (at least) the implicit statement for non-payable check.
    """
    with ape.reverts(NonPayableError):
        contract.foo_method(5, 1, sender=account, value=1)


def test_no_default_method(contract, account):
    """
    Covers the implicit check for fallback not defined.
    """
    with ape.reverts(FallbackNotDefinedError):
        contract(sender=account)


def test_foo_method_no_args(contract, account):
    """
    Covers the statement from the autogenerated method.
    """
    receipt = contract.foo_method(sender=account)
    assert not receipt.failed


def test_foo_method_one_arg(contract, account):
    """
    Covers the statement from the autogenerated method.
    """
    receipt = contract.foo_method(1, sender=account)
    assert not receipt.failed
